### ISSUE TITLE
获取文件类型和大小的时候会出现这个错误

### ISSUE THREAD

**Issue by jianyan74** [l396635210/flysystem-qiniu#1]
array_key_exists() expects parameter 2 to be array, integer given

**Comment by l396635210** [comment]
已经修复，以为不会有人用呢。所以一直没看，不好意思，谢谢使用

**Comment by jianyan74** [comment]
哈哈 准备持续集成在自己的项目里面 加油鸭

**Comment by l396635210** [comment]
[overtrue/flysystem-qiniu](https://packagist.org/packages/overtrue/flysystem-qiniu)
他这个比较成熟，用的人也挺多（你可以选择这个使用）。只是我用[helios-ag/FMElfinderBundle](https://github.com/helios-ag/FMElfinderBundle)时复制文件时发现文件中有空格的话会有问题，看了下源码挺简单就自己写了下

**Comment by jianyan74** [comment]
噢噢 我都是在用百度编辑器
