### ISSUE TITLE
请在composer.json中允许php8.0版本加载此包

### ISSUE THREAD

**Issue by chenjinnian** [l396635210/flysystem-qiniu#3]
如题，请添加允许PHP8.0，"php": "^7.0 || ^8.0"

[QQ截图20210112204615](https://user-images.githubusercontent.com/52153807/104316339-4bd82f80-5517-11eb-9d31-e013c256b807.png)

**Comment by chenjinnian** [comment]
或者："php": ">=7.0"

**Comment by l396635210** [comment]
已经添加

**Comment by chenjinnian** [comment]
感谢，真是太快啦。
